### PR TITLE
Automatically Like All the Post #6

### LINKED ISSUE #6: Automatically Like All the Post
* ##  Like Automation
* Open the Instagram and Start Liking All the Post and Scroll down and repeat the steps.

### PR DESCRIPTION
**Pull request by Akash20x**
## Related Issue
  - Automatically Like All the Post 

Closes: 
#6 

### Describe the changes you've made
Added a autoliker function to like posts of Instagram feed up to a certain limit.

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
### Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

### CODE REVIEW

**Comment by abhigoyani** [comment]
when searching the user name it gets stuck while running the script.

**Comment by Akash20x** [comment]
Ok I will check

**Comment by Akash20x** [comment]
@abhigoyani , I checked and updated the code for like posts on username search and tested it and it works properly.
You can check it now.

@harikanani Please check my pull request and merge it.

**Comment by Akash20x** [comment]
@abhigoyani  , I checked and updated the code for like posts on username search and tested it and it works properly.
You can check it now.

@harikanani  Please check my pull request and merge it.

**Comment by harikanani** [comment]
@Akash20x , I've checked your code and it's not working. as @abhigoyani tells you that code gets stuck after searching username. check your code and if it's running on your local code then share a video or screenshot. I'm sharing what I get from my side.

# Screenshot
* Error Code
image

* Code Stuck after searching
image

**Review by harikanani — CHANGES_REQUESTED** [review]
# Changes to be done  
* Please Change the main.py file

The error I got while running code
image

the code gets stuck after searching username
image

**Comment by Akash20x** [comment]
Hey the above code works perfectly fine on my laptop but in some case it stuck, but after 5 - 6 seconds it automatically go to the post and starting like it

But sometimes it stuck and break, Run again the program will fix this. 

I will share a video to demonstrate it properly

**Comment by Akash20x** [comment]
I fix this, try it

**Comment by harikanani** [comment]
Hey @Akash20x ,
I've checked your code and now it's working fine but let me know can you do any changes?
it first unlike the post and then like the post again.
fix this issue and then make a pr

**Review by harikanani — CHANGES_REQUESTED** [review]
### Bug to be Fix
it first unlike the liked post and then link it.

**Comment by Akash20x** [comment]
Please check now, I fix the above bug

**Review by harikanani — CHANGES_REQUESTED** [review]
# Program terminated abnormally
when there are no next posts then the program is abnormally terminating
for reference checkout the error message

## Screenshot
image

**Comment by Akash20x** [comment]
hey @harikanani,  the main solution for the issue is already fulfilled. So please close this issue.
For minor bugs , you encounter please open another issue. 
As I consume a lot of time on this issue, I think you need to merge this and then open another issue for small problems and assign someone else.

**Comment by harikanani** [comment]
@Akash20x , there's one more error in code that, goto_home function is not indented check it and update it and then make a Final PR.

**Review by harikanani — CHANGES_REQUESTED** [review]
def go_home() function is not indented currently

**Comment by Akash20x** [comment]
Done

**Comment by harikanani** [comment]
Thank you for contributing to this project @Akash20x 
Happy Hacking 😊.

@all-contributors please add @Akash20x  for code

**Review by harikanani — APPROVED** [review]

**Pull request merged**
